### ISSUE TITLE
There is a typing error on ReadMe.md

### ISSUE THREAD

**Issue by ainch** [Kyziridis/BipedalWalker-v2#2]
you have to change 

"Other dependencies : Keras, matplotlib, numpy, random, rensor flow"

into

Other dependencies : Keras, matplotlib, numpy, random, tensorflow

**Comment by Kyziridis** [comment]
> you have to change
> 
> "Other dependencies : Keras, matplotlib, numpy, random, rensor flow"
> 
> into
> 
> Other dependencies : Keras, matplotlib, numpy, random, tensorflow

Thank you for your comment, I already fix the error. If you have any suggestion about the algorithms or anything around this game please send me.

Thank u in Advance

**Comment by Kyziridis** [comment]
Done
